apiVersion: apps/v1
kind: Deployment
metadata:
  name: productionno-1-deployment
spec:
  selector:
    matchLabels:
      app: productionno-1-deployment
  replicas: 6
  template:
    metadata:
      labels:
        app: productionno-1-deployment
    spec:
      containers:
      - name: productionno-1-deployment
        image: manjugoud/productionno-1:36
        ports:
        - containerPort: 8080
