apiVersion: v1
kind: Service
metadata:
  name: productionno-1-service
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 9000
      targetPort: 8080
  selector:
    app: productionno-1-deployment
